In [1]:
import pickle

In [2]:
#reopening data
class Company(object):
    def __init__(self, rec):
        self.rec = rec


#opens the file to make sure it worked    
with open('recent_comp.pkl', 'rb') as input:
    rdatac = pickle.load(input, encoding='latin1')    

recent_complete = rdatac.rec 

In [137]:
recent_data = recent_complete.dropna()

In [6]:
import numpy as np
#Since my data has been normalized by the NSC Im not concerned with body weight, so for a given
#lifter, I'll use his country of origin, age and the years he has competed and plot that
#against his coefficient.
X = np.array(recent_data[['LC', 'CC', 'Birth', 'Age', 'Year']])
y = np.array(recent_data['NSC'])

In [7]:
from sklearn.neighbors import KNeighborsRegressor

In [8]:
nei = KNeighborsRegressor(n_neighbors=100, weights='distance',
                          algorithm='ball_tree', leaf_size=1000, metric='manhattan')

In [9]:
from sklearn.cross_validation import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [11]:
nei.fit(X_train, y_train)

KNeighborsRegressor(algorithm='ball_tree', leaf_size=1000, metric='manhattan',
          metric_params=None, n_neighbors=100, p=2, weights='distance')

In [12]:
nei.predict([6261,48,1998,18,2016])

array([-160.48709214])

In [24]:
class Company1(object):
    def __init__(self, mod):
        self.mod = mod

with open('nei_model.pkl', 'wb') as output:
    recent_c = Company1(nei)
    pickle.dump(recent_c, output, protocol=2)

In [17]:
#opens the file to make sure it worked    
with open('nei_model.pkl', 'rb') as input:
    nei_model_predict = pickle.load(input)    

nei_model_predict3 = nei_model_predict.mod

In [18]:
nei_model_predict3.predict([6261,48,1998,18,2016])

array([-160.48709214])

In [20]:
import dill
with open('nei_model.dill', 'rb') as input:
    nei_model_pred = dill.load(input)

In [21]:
nei_model_pred.predict([6261,48,1998,18,2016])

array([-160.48709214])

In [4]:
import pycountry
from geopy.geocoders import Nominatim

In [5]:
geolocator = Nominatim()

In [6]:
location = geolocator.geocode("USA")

In [7]:
print((location.latitude, location.longitude))

(39.7837304, -100.4458824)


In [8]:
location2 = geolocator.geocode("PUR")

In [9]:
print((location2.latitude, location2.longitude))

(23.0619849, 101.1407285)


In [41]:
def lat(row):
    if row['Country'] == 'DEN':
        return 55.72
    else:
        location = geolocator.geocode(row['Country'])
        return location.latitude

In [ ]:
recent_data['Lat'] = recent_data.apply(lambda row: lat(row),axis=1)

In [79]:
location2 = geolocator.geocode("Puerto Rico")

In [80]:
print(location2.address)

Puerto Rico, United States of America


In [ ]:
def long(row):
    location1 = geolocator.geocode(row['Country'])
    return location1.longitude

In [54]:
location = geolocator.geocode('Puerto Rico')
print(location.latitude)

18.2017809


In [ ]:
country = pycountry.countries.get(name='Bulgary')

In [75]:
country.alpha2

'VE'

In [83]:
from bs4 import BeautifulSoup
import requests

In [84]:
r = requests.get("http://www.iwf.net/focus-on-iwf/federations/?federation=panamerica")
soup = BeautifulSoup(r.content)
rows = soup.find_all("tr")

In [115]:
country_codes = []
country_names = []
federations = ['http://www.iwf.net/focus-on-iwf/federations/?federation=panamerica',
               'http://www.iwf.net/focus-on-iwf/federations/?federation=europe',
               'http://www.iwf.net/focus-on-iwf/federations/?federation=asia',
               'http://www.iwf.net/focus-on-iwf/federations/?federation=oceania',
               'http://www.iwf.net/focus-on-iwf/federations/?federation=africa']

for link in federations:
    r = requests.get(link)
    soup = BeautifulSoup(r.content)
    rows = soup.find_all("tr")
    for row in rows:
        cells = row.find_all('td')
        for i, cell in enumerate(cells):
            if i == 1:
                country_codes.append(cell.text.strip().lower())
            
        for i, cell in enumerate(cells):
            if i == 0:
                country_names.append(cell.text.strip())
            

In [116]:
country_codes[:5]

['code', 'ant', 'arg', 'aru', 'bah']

In [117]:
country_dict = {}

for i in range(len(country_codes)):
    if country_codes[i] not in country_dict:
        country_dict[country_codes[i]] = country_names[i]

In [118]:
country_dict

{'afg': 'AFGHANISTAN',
 'alb': 'ALBANIA',
 'alg': 'ALGERIA',
 'ant': 'ANTIGUA AND BARBUDA',
 'arg': 'ARGENTINA',
 'arm': 'ARMENIA',
 'aru': 'ARUBA',
 'asa': 'AMERICAN SAMOA',
 'aus': 'AUSTRALIA',
 'aut': 'AUSTRIA',
 'aze': 'AZERBAIJAN',
 'bah': 'BAHAMAS',
 'ban': 'BANGLADESH',
 'bar': 'BARBADOS',
 'bel': 'BELGIUM',
 'bhu': 'BHUTAN',
 'bih': 'BOSNIA AND HERZEGOVINA',
 'biz': 'BELIZE',
 'blr': 'BELARUS',
 'bol': 'BOLIVIA',
 'bot': 'BOTSWANA',
 'bra': 'BRAZIL',
 'brn': 'BAHRAIN',
 'bru': 'BRUNEI DARUSSALAM',
 'bul': 'BULGARIA',
 'cam': 'CAMBODIA',
 'can': 'CANADA',
 'cay': 'CAYMAN ISLANDS',
 'cgo': 'CONGO',
 'chi': 'CHILE',
 'chn': "PEOPLE'S REPUBLIC OF CHINA",
 'cmr': 'CAMEROUN',
 'cod': 'DEMOCRATIC REPUBLIC OF THE CONGO',
 'code': 'Member',
 'cok': 'COOK ISLANDS',
 'col': 'COLOMBIA',
 'com': 'COMOROS',
 'crc': 'COSTA RICA',
 'cro': 'CROATIA',
 'cub': 'CUBA',
 'cur': 'CURACAO',
 'cyp': 'CYPRUS',
 'cze': 'CZECH REPUBLIC',
 'den': 'DENMARK',
 'dom': 'DOMINICAN REPUBLIC',
 'ecu': 'ECUADOR',

In [139]:
#adding country name
def CN(row):
    country_lower = row['Country'].lower()
    try:
        return country_dict[country_lower]
    except:
        return 'NO'

In [151]:
recent_data.head()

Lifter  LC Country  CC  Age  Birth  Weight  Year  Snatch  \
0              IVANOV Ivan   0     BUL   0   27   1971   55.86  1998   122.5   
1  VARGAS William Trujillo   1     CUB   1   28   1970   55.94  1998   127.5   
2        JIGAU Adrian Ioan   2     ROU   2   28   1970   55.79  1998   117.5   
3    ALVAREZ BOULET Sergio   3     CUB   1   19   1979   55.75  1998   115.0   
4              BONNEL Eric   4     FRA   3   24   1974   55.50  1998   110.0   

   Clean and Jerk  Total        NSC Country Name  
0           160.0  282.5 -22.412757     BULGARIA  
1           155.0  282.5 -22.882967         CUBA  
2           145.0  262.5 -41.999190      ROMANIA  
3           142.5  257.5 -46.761965         CUBA  
4           142.5  252.5 -50.264201       FRANCE

In [140]:
recent_data['Country Name'] = recent_data.apply(lambda row: CN(row),axis=1)

//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [143]:
recent_data = recent_data[recent_data['Country Name']!= 'NO']

In [ ]:
def long(row):
    location1 = geolocator.geocode(row['Country Name'])
    return location1.longitude

In [147]:
countries_lat = {}
countries_long = {}

for country in country_names:
    if country not in countries_lat:
        countries_lat[country]= geolocator.geocode(country).latitude
        countries_long[country]= geolocator.geocode(country).longitude

In [152]:
def lat(row):
    return countries_lat[row['Country Name']]

In [155]:
def long(row):
    return countries_long[row['Country Name']]

In [153]:
recent_data['Lat'] = recent_data.apply(lambda row: lat(row),axis=1)

In [156]:
recent_data['Long'] = recent_data.apply(lambda row: long(row),axis=1)

In [157]:
recent_data.head()

Lifter  LC Country  CC  Age  Birth  Weight  Year  Snatch  \
0              IVANOV Ivan   0     BUL   0   27   1971   55.86  1998   122.5   
1  VARGAS William Trujillo   1     CUB   1   28   1970   55.94  1998   127.5   
2        JIGAU Adrian Ioan   2     ROU   2   28   1970   55.79  1998   117.5   
3    ALVAREZ BOULET Sergio   3     CUB   1   19   1979   55.75  1998   115.0   
4              BONNEL Eric   4     FRA   3   24   1974   55.50  1998   110.0   

   Clean and Jerk  Total        NSC Country Name        Lat       Long  
0           160.0  282.5 -22.412757     BULGARIA  42.607397  25.485662  
1           155.0  282.5 -22.882967         CUBA  23.013134 -80.832875  
2           145.0  262.5 -41.999190      ROMANIA  45.985213  24.685923  
3           142.5  257.5 -46.761965         CUBA  23.013134 -80.832875  
4           142.5  252.5 -50.264201       FRANCE  46.603354   1.888334

In [158]:
recent_data = recent_data[['LC','Lifter','Weight', 'Age','Birth','Country Name','Lat', 'Long', 'Year', 'Snatch','Clean and Jerk','Total','NSC']]

In [159]:
recent_data.head()

LC                   Lifter  Weight  Age  Birth Country Name        Lat  \
0   0              IVANOV Ivan   55.86   27   1971     BULGARIA  42.607397   
1   1  VARGAS William Trujillo   55.94   28   1970         CUBA  23.013134   
2   2        JIGAU Adrian Ioan   55.79   28   1970      ROMANIA  45.985213   
3   3    ALVAREZ BOULET Sergio   55.75   19   1979         CUBA  23.013134   
4   4              BONNEL Eric   55.50   24   1974       FRANCE  46.603354   

        Long  Year  Snatch  Clean and Jerk  Total        NSC  
0  25.485662  1998   122.5           160.0  282.5 -22.412757  
1 -80.832875  1998   127.5           155.0  282.5 -22.882967  
2  24.685923  1998   117.5           145.0  262.5 -41.999190  
3 -80.832875  1998   115.0           142.5  257.5 -46.761965  
4   1.888334  1998   110.0           142.5  252.5 -50.264201

In [160]:
#saving data with lat-long
class Company(object):
    def __init__(self, recgeo):
        self.recgeo = recgeo

with open('recent_geo.pkl', 'wb') as output:
    recent_c = Company(recent_data)
    pickle.dump(recent_c, output, pickle.HIGHEST_PROTOCOL)

In [163]:
#opens the file to make sure it worked    
with open('recent_geo.pkl', 'rb') as input:
    rgeo = pickle.load(input)  
r_geo = rgeo.recgeo   

In [164]:
r_geo.head()

LC                   Lifter  Weight  Age  Birth Country Name        Lat  \
0   0              IVANOV Ivan   55.86   27   1971     BULGARIA  42.607397   
1   1  VARGAS William Trujillo   55.94   28   1970         CUBA  23.013134   
2   2        JIGAU Adrian Ioan   55.79   28   1970      ROMANIA  45.985213   
3   3    ALVAREZ BOULET Sergio   55.75   19   1979         CUBA  23.013134   
4   4              BONNEL Eric   55.50   24   1974       FRANCE  46.603354   

        Long  Year  Snatch  Clean and Jerk  Total        NSC  
0  25.485662  1998   122.5           160.0  282.5 -22.412757  
1 -80.832875  1998   127.5           155.0  282.5 -22.882967  
2  24.685923  1998   117.5           145.0  262.5 -41.999190  
3 -80.832875  1998   115.0           142.5  257.5 -46.761965  
4   1.888334  1998   110.0           142.5  252.5 -50.264201

In [166]:
import numpy as np

In [167]:
X = np.array(r_geo[['LC', 'Weight','Lat','Long', 'Age','Birth', 'Year']])
y = np.array(r_geo['NSC'])

In [168]:
from sklearn.neighbors import KNeighborsRegressor

In [169]:
nei = KNeighborsRegressor(n_neighbors=100, weights='distance',
                          algorithm='ball_tree', leaf_size=1000, metric='manhattan')

In [170]:
from sklearn.cross_validation import train_test_split

In [171]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [172]:
nei.fit(X_train, y_train)

KNeighborsRegressor(algorithm='ball_tree', leaf_size=1000, metric='manhattan',
          metric_params=None, n_neighbors=100, p=2, weights='distance')

In [174]:
r_geo[r_geo['Country Name']=='PUERTO RICO']

LC                         Lifter  Weight  Age  Birth Country Name  \
191     191                 MARTINEZ Julio   73.60   20   1978  PUERTO RICO   
492     451       ARIAS Edwin Nieves-Arias   60.50   22   1977  PUERTO RICO   
519     463                MARTINEZ Marcos   68.06   19   1980  PUERTO RICO   
784     632                 HERNANDEZ Eric  103.90   21   1978  PUERTO RICO   
856     682                GONZALES Edries  138.89   27   1972  PUERTO RICO   
931     451       ARIAS Edwin Nieves-Arias   60.83   23   1977  PUERTO RICO   
1034    770              SAURI CRUZ Carlos   76.92   26   1974  PUERTO RICO   
1979   1209              MARTINEZ Wilfredo   68.60   22   1981  PUERTO RICO   
1983   1212                   TORRES Wayne   67.25   17   1986  PUERTO RICO   
2085   1255               CARTAGENA Moises   84.49   28   1975  PUERTO RICO   
2105   1264                  CRESPO Dennis   88.30   24   1979  PUERTO RICO   
2140   1276             LOPEZ Jose Gabriel   88.90   17   1986  PUERTO RICO   
2469   1276             LOPEZ Jose Gabriel   91.05   18   1986  PUERTO RICO   
2480   1403                  ORTIZ Anthony   91.75   23   1981  PUERTO RICO   
2871   1276             LOPEZ Jose Gabriel   93.00   19   1986  PUERTO RICO   
3125   1209              MARTINEZ Wilfredo   68.90   25   1981  PUERTO RICO   
3329   1764                   NIEVES David   92.90   23   1983  PUERTO RICO   
4091   2101                     ORTIZ Luis   61.29   21   1987  PUERTO RICO   
4192   2135  SERRANO RIVERA Jerami Antonio   68.63   20   1988  PUERTO RICO   
4269    770              SAURI CRUZ Carlos   76.34   34   1974  PUERTO RICO   
4300   2181     SANTIAGO RODRIGUEZ Ricardo   74.60   17   1991  PUERTO RICO   
4373   1255               CARTAGENA Moises   84.60   33   1975  PUERTO RICO   
4477   2243     ROSADO CRUZ Roberto Carlos   91.86   21   1987  PUERTO RICO   
4572   2286            MARCIAL Juan Carlos  103.37   29   1979  PUERTO RICO   
4575   2289              SEPULVEDA Roberto  104.11   25   1983  PUERTO RICO   
4650   2323                   RAMOS Carlos  118.17   23   1985  PUERTO RICO   
4813   2443              LUIS Lebron Colon   55.82   14   1995  PUERTO RICO   
4828   2458    GUZMAN PEREZ Bryan Gilberto   43.74   12   1997  PUERTO RICO   
4832   2462      RODRIGUEZ CORTES Yabdiell   45.60   11   1998  PUERTO RICO   
4997   2570            WILLIAM Aviles Cruz   56.92   15   1994  PUERTO RICO   
...     ...                            ...     ...  ...    ...          ...   
8984   3376     CARLOS RUBEN Negron Torres   61.73   20   1992  PUERTO RICO   
9139   4423           LANDRO RAMOS Luis G.   66.88   22   1990  PUERTO RICO   
9146   3349       RIVERA MARTINEZ Jesus J.   66.99   25   1987  PUERTO RICO   
9187   4443       MORALES FIGUEROA John L.   66.18   19   1993  PUERTO RICO   
9305    770              SAURI CRUZ Carlos   76.62   38   1974  PUERTO RICO   
9669   1255               CARTAGENA Moises   91.42   37   1975  PUERTO RICO   
9821   3621                    MARTE Keven  104.20   20   1992  PUERTO RICO   
9952   3744                 BONILLA Javier  110.67   26   1986  PUERTO RICO   
10086  4293                CARABALLO Ariel   55.54   24   1989  PUERTO RICO   
10477  3353                    LANDRO Luis   67.58   23   1990  PUERTO RICO   
10718  3372            ALEXANDER Hernandez   75.88   23   1990  PUERTO RICO   
10758  3572                   JEFFREY Cruz   76.66   24   1989  PUERTO RICO   
11218  3621                    MARTE Keven  101.44   21   1992  PUERTO RICO   
11504  2458    GUZMAN PEREZ Bryan Gilberto   55.24   17   1997  PUERTO RICO   
11706  3257                   OLMEDO Ruben   60.10   30   1984  PUERTO RICO   
11859  3353                    LANDRO Luis   68.70   24   1990  PUERTO RICO   
11943  5515                  SANCHEZ Jorge   64.05   16   1998  PUERTO RICO   
12168  5598                RODRIGUEZ Ruben   75.02   17   1997  PUERTO RICO   
12305  3372            ALEXANDER Hernandez   81.18   24   1

In [178]:
nei.predict([6119,18.201781,-66.584125,18,1998,2016])

array([-129.89497315])

In [241]:
class Company2(object):
    def __init__(self, geo):
        self.geo = geo

with open('nei_improve.pkl', 'wb') as output:
    recent_imp = Company2(nei)
    pickle.dump(recent_imp, output, protocol=2)
    

In [185]:
#opens the file to make sure it worked    
with open('nei_improve.pkl', 'rb') as input:
    nei_model_imp = pickle.load(input)    

model_imp = nei_model_imp.geo

In [186]:
model_imp.predict([6119,18.201781,-66.584125,18,1998,2016])

array([-129.89497315])

In [216]:
countries_df = recent_data[['Country Name', 'Lat', 'Long']]

In [231]:
countries_unique = countries_df.drop_duplicates()

In [232]:
len(countries_unique)

161

In [239]:
class Company3(object):
    def __init__(self, cu):
        self.cu = cu

with open('unique_countries.pkl', 'wb') as output:
    c_unique = Company3(countries_unique)
    pickle.dump(c_unique, output, protocol=2)

In [243]:
#opens the file to make sure it worked    
with open('unique_countries.pkl', 'rb') as input:
    uni_c = pickle.load(input)    

unique_c_list = uni_c.cu

In [245]:
unique_c_list.head()

Country Name        Lat       Long
0     BULGARIA  42.607397  25.485662
1         CUBA  23.013134 -80.832875
2      ROMANIA  45.985213  24.685923
4       FRANCE  46.603354   1.888334
5      UKRAINE  49.487197  31.271832