In [1]:
import pickle

In [2]:
#reopening data
class Company(object):
    def __init__(self, rec):
        self.rec = rec


#opens the file to make sure it worked    
with open('recent_comp.pkl', 'rb') as input:
    rdatac = pickle.load(input, encoding='latin1')    

recent_complete = rdatac.rec 

In [4]:
recent_data = recent_complete.dropna()

In [6]:
import numpy as np
#Since my data has been normalized by the NSC Im not concerned with body weight, so for a given
#lifter, I'll use his country of origin, age and the years he has competed and plot that
#against his coefficient.
X = np.array(recent_data[['LC', 'CC', 'Birth', 'Age', 'Year']])
y = np.array(recent_data['NSC'])

In [7]:
from sklearn.neighbors import KNeighborsRegressor

In [8]:
nei = KNeighborsRegressor(n_neighbors=100, weights='distance',
                          algorithm='ball_tree', leaf_size=1000, metric='manhattan')

In [9]:
from sklearn.cross_validation import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=100)

In [11]:
nei.fit(X_train, y_train)

KNeighborsRegressor(algorithm='ball_tree', leaf_size=1000, metric='manhattan',
          metric_params=None, n_neighbors=100, p=2, weights='distance')

In [12]:
nei.predict([6261,48,1998,18,2016])

array([-160.48709214])

In [24]:
class Company1(object):
    def __init__(self, mod):
        self.mod = mod

with open('nei_model.pkl', 'wb') as output:
    recent_c = Company1(nei)
    pickle.dump(recent_c, output, protocol=2)

In [17]:
#opens the file to make sure it worked    
with open('nei_model.pkl', 'rb') as input:
    nei_model_predict = pickle.load(input)    

nei_model_predict3 = nei_model_predict.mod

In [18]:
nei_model_predict3.predict([6261,48,1998,18,2016])

array([-160.48709214])

In [20]:
import dill
with open('nei_model.dill', 'rb') as input:
    nei_model_pred = dill.load(input)

In [21]:
nei_model_pred.predict([6261,48,1998,18,2016])

array([-160.48709214])

In [22]:
from scipy import sparse